name: Daily Test Execution.

# configure manual trigger
on:
  workflow_dispatch:
    inputs:
      test_plan_key:
        description: 'Test Plan issue key'
        required: false
        default: ''

jobs:
  UAT-Smoke-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Smoke Tests
        run: |
          npm install
    
